services:
  client:
    build:
      context: .
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./:/usr/ishiko/client/
    networks:
      - dev
    environment:
      - BASE_URL=http://localhost:8000
      - NEXT_PUBLIC_BASE_URL=http://localhost:8000
      - API_URL=http://api:8080
      - NODE_ENV=development

networks:
  dev:
    external: true
