services:
  test:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ishiko
      POSTGRES_PASSWORD: ishiko
      POSTGRES_DB: test
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/scripts:ro
      - ./init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh