services:
  dev:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ishiko
      POSTGRES_PASSWORD: ishiko
      POSTGRES_DB: dev
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
