services:
  db-dev:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ishiko
      POSTGRES_PASSWORD: ishiko
      POSTGRES_DB: dev
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/scripts:ro
      - ./init-dev-db.sh:/docker-entrypoint-initdb.d/init-dev-db.sh
    networks:
      - dev

networks:
  dev:
