services:
  db-dev:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ishiko
      POSTGRES_PASSWORD: ishiko
      POSTGRES_DB: dev
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - type: bind
        source: ./schema.sql
        target: /docker-entrypoint-initdb.d/schema.sql
        read_only: true
    networks:
      - dev

networks:
  dev:
    external: true
